server:
  port: 9898
#
#admin.rules.workbenchURL=http://localhost:8080/kie-drools-wb-6.3.0.Final-wildfly8
#admin.rules.repoContextPath=/maven2/
#admin.rules.username=admin
#admin.rules.password=admin
#
#logging.level.com.rmpader.springdrools=TRACE

#management:
#  endpoints:
#   web:
#     exposure:
#      include: *

spring:
  r2dbc:
    url: r2dbcs:mysql://localhost/vaccine
    username: root
    password: 'N09122182313n'

logging:
  level:
    co.nilin: DEBUG
    org.springframework.security: DEBUG
  file:
    name: C:/Users/Fatemeh_ip/logs/ava_profile.log


